### ISSUE TITLE
土豆的视频无法播放

### ISSUE THREAD

**Issue by HuberyHuan** [Goshin/Yatto#2]
使用 **python3 yatto.py  "http://www.tudou.com/albumplay/Lqfme5hSolM/wNMcatvqbWU.html"** 得到以下报错
`2016-05-03 19:55:35,055 - INFO - Parsing page...`
`2016-05-03 19:55:35,631 - INFO - Tudou danmaku detected`
`2016-05-03 19:55:35,631 - INFO - Processing danmaku segment 0/4`
`2016-05-03 19:55:35,781 - INFO - Processing danmaku segment 1/4`
`2016-05-03 19:55:36,188 - INFO - Processing danmaku segment 2/4`
`2016-05-03 19:55:37,005 - INFO - Processing danmaku segment 3/4`
`2016-05-03 19:55:37,150 - INFO - Processing danmaku segment 4/4`
`2016-05-03 19:55:37,332 - INFO - Fetching danmaku`
`2016-05-03 19:55:37,332 - ERROR - get video size failed list index out of range`
`2016-05-03 19:55:37,345 - INFO - Invoking Danmaku2ASS, converting to /var/folders/r5/82pn5t7s0nv38ywttt5hzvn80000gn/T/tmp-danmaku2ass-z_7vn3y5.ass`
`Traceback (most recent call last):`
`File "yatto.py", line 343, in main`
`danmaku_file = convert_comments(danmaku, get_video_size(video_url))`
`File "yatto.py", line 215, in convert_comments`
    `duration_marquee': min(max(6.75 * video_size[0] / video_size[1] - 4, 3.0), 8.0),`
**`ZeroDivisionError: float division by zero`**
`2016-05-03 19:55:37,345 - ERROR - Download danmaku failed, float division by zero`
`2016-05-03 19:55:37,347 - ERROR - Parse video page failed`

试了几个不同的网址仍然是这个报错。请问是该如何解决？

**Comment by Goshin** [comment]
感谢反馈，flvcd 停止了优酷和土豆的解析，我会尽快更换成 you-get 的。

**Comment by Goshin** [comment]
已经解决

**Comment by fanghuan** [comment]
谢谢你，另请教一个问题，土豆网的弹幕是地址是如何得到？优酷的弹幕地址也能通过同样的方法得到吗？谢谢告知。

**Comment by Goshin** [comment]
@fanghuan 

> 谢谢你，另请教一个问题，土豆网的弹幕是地址是如何得到？优酷的弹幕地址也能通过同样的方法得到吗？谢谢告知。

弹幕地址：http://service.danmu.tudou.com/list?mat=0&mcount=1&ct=1001&uid=0&iid=132648348
mat 表示时间起点（分钟），mcount 表示分钟数，如 mat=1&mcount=5 为时间 1 ~ 6 min 的弹幕。
其中 `iid` 从页面获取，参见：https://github.com/Goshin/Yatto/blob/master/src/yatto.py#L170-L171

不知道优酷什么时候有的弹幕，不过地址应该不一样吧，有时间也加上优酷弹幕的解析吧。

**Comment by fanghuan** [comment]
好的，明白了，谢谢解答，期待更新。
