### ISSUE TITLE
弹幕ass写入不刷新关闭导致播放时未能读取弹幕

### ISSUE THREAD

**Issue by chinuno-usami** [Goshin/Yatto#3]
转换弹幕时不flush不close导致ass文件内容停留在缓冲区没能写入到硬盘，播放器播放时取不到尚未写入硬盘的ass内容。
在[136和137](https://github.com/Goshin/Yatto/blob/master/src/yatto.py#L136,L137)两行应该缩进往前一级，不论有没有转换成功都要把内容写入硬盘

**Comment by Goshin** [comment]
非常感谢，能请你发一个 PR 吗？或是我直接 patch？
