### ISSUE TITLE
yatto解析土豆的结果与 you-get 有差别

### ISSUE THREAD

**Issue by HuberyHuan** [Goshin/Yatto#5]
使用**yatto.py  "http://www.tudou.com/albumplay/w2FoI7eigmU/e_BnSIIUswE.html"** 得到
2016-05-07 21:04:34,711 - INFO - Parsing page...
.... 省略 ...
/var/folders/r5/82pn5t7s0nv38ywttt5hzvn80000gn/T/tmp-danmaku2ass-yvsity72.ass
2016-05-07 21:04:39,920 - INFO - Buffering video header, this may take a while
Playing: edl://**`http://111.1.52.237/youku/677761A045C3F71CB2E9064E1/0300080700520B4897684803BAF2B1372E4F60-B276-E0A4-DD75-B24FFD40705C.mp4;http://112.25.50.114/youku/657761A0722477895C0BF2EBF/0300080702520B4897684803BAF2B1372E4F60-B276-E0A4-DD75-B24FFD40705C.mp4;http://112.25.17.245/youku/697EC3408D647788CDE9137E5/0300080704520B4897684803BAF2B1372E4F60-B276-E0A4-DD75-B24FFD40705C.mp4;http://111.1.52.209/youku/698113920D6D4C722B6E0F370A/0300080706520B4897684803BAF2B1372E4F60-B276-E0A4-DD75-B24FFD40705C.mp4`**

只能得到4个 mp4片段，而用
**you-get -u "http://www.tudou.com/albumplay/w2FoI7eigmU/e_BnSIIUswE.html"** 可以得到7个 mp4片段
Real URLs:
**`http://111.1.52.237/youku/6979D78893D4C722B76486AFB/0300080700520B4897684803BAF2B1372E4F60-B276-E0A4-DD75-B24FFD40705C.mp4
http://112.25.45.52/youku/697B1279AD74D795093563736/0300080701520B4897684803BAF2B1372E4F60-B276-E0A4-DD75-B24FFD40705C.mp4
http://112.25.50.114/youku/697C4D6AF0C4D795221BE5FC1/0300080702520B4897684803BAF2B1372E4F60-B276-E0A4-DD75-B24FFD40705C.mp4
http://112.25.47.102/youku/677B12799784E79709CA16201/0300080703520B4897684803BAF2B1372E4F60-B276-E0A4-DD75-B24FFD40705C.mp4
http://112.25.17.245/youku/6579D78878B43780FCA8C550D/0300080704520B4897684803BAF2B1372E4F60-B276-E0A4-DD75-B24FFD40705C.mp4
http://112.25.47.114/youku/697FFE3D7C63C773BB34C4794/0300080705520B4897684803BAF2B1372E4F60-B276-E0A4-DD75-B24FFD40705C.mp4
http://111.1.52.209/youku/657C4D6AA474E723A3DD05A75/0300080706520B4897684803BAF2B1372E4F60-B276-E0A4-DD75-B24FFD40705C.mp4`**
对比这二者的结果，发现 yatto 挑选了 you-get 结果的1,3,5,7个片段，我觉得是_**正则表达式出了 bug，希望修复。**_
注: 我的系统信息

> `python3 -V`
> Python 3.5.1
> `uname -a`
> 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64

**Comment by Goshin** [comment]
十分感谢，我只在 Windows 上测试了，不知道写错了。
